### ISSUE TITLE
smartdenovo make error

### ISSUE THREAD

**Issue by liguiyang410** [ruanjue/smartdenovo#18]
when make in fold smartdenovo, errors were showed as follows:
/tmp/ccTfg5aF.o: In function `merge_bubbles_strgraph':
wtlay.c:(.text+0x984d): undefined reference to `cut_biedge_strgraph2'
wtlay.c:(.text+0x9861): undefined reference to `cut_biedge_strgraph2'
wtlay.c:(.text+0x992d): undefined reference to `cut_biedge_strgraph2'
wtlay.c:(.text+0x994a): undefined reference to `cut_biedge_strgraph2'
collect2: error: ld returned 1 exit status
Makefile:48: recipe for target 'wtlay' failed
make: *** [wtlay] Error 1

**Comment by ruanjue** [comment]
Please tell me your gcc version. Try to modify https://github.com/ruanjue/smartdenovo/blob/5cc1356bffb87197b0fb9b835cfe1adc5a764dc6/Makefile#L48 into `$(CC) $(CFLAGS) -o wtlay file_reader.c wtlay.c  wtlay.h $(GLIBS)`, then make wtlay again.

**Comment by liguiyang410** [comment]
GCC 4.8 .   I modified the line 48, but still the same errors.

**Comment by emaleckova** [comment]
I also had troubles installing SMARTdenovo, similar to those described here as well as in issue #22. Since it took me several tries to install successfully, I would like to share what helped in my case:

1. Changes in the `Makefile` as metioned here
2. Removing lines 95 to 97 and 832 to 834 in `wtlay.h` as mentioned here
3. Add `static` before **all** five occurrences of `inline` (lines 491 to 518) in `wtlay.h`

For completeness, I work on `Ubuntu 19.04` and run `gcc 8.3.0`.

**Comment by ruanjue** [comment]
Thanks!

**Comment by miltongr21** [comment]
> I also had trouble installing SMARTdenovo, similar to those described here as well as in issue #22. Since it took me several tries to install successfully, I would like to share what helped in my case:
> 
> 1. Changes in the `Makefile` as mentioned here
> 2. Removing lines 95 to 97 and 832 to 834 in `wtlay.h` as mentioned here
> 3. Add `static` before **all** five occurrences of `inline` (lines 491 to 518) in `wtlay.h`
> 
> For completeness, I work on `Ubuntu 19.04` and run `gcc 8.3.0`.

Genious!

**Comment by miltongr21** [comment]
# @emaleckova 
This solved the problem for me!
Thanks bro!

**Comment by cfz1998** [comment]
> I also had trouble installing SMARTdenovo, similar to those described here as well as in issue #22. Since it took me several tries to install successfully, I would like to share what helped in my case:
> 
> 1. Changes in the `Makefile` as mentioned here
> 2. Removing lines 95 to 97 and 832 to 834 in `wtlay.h` as mentioned here
> 3. Add `static` before **all** five occurrences of `inline` (lines 491 to 518) in `wtlay.h`
> 
> For completeness, I work on `Ubuntu 19.04` and run `gcc 8.3.0`.

Thanks！
